### ISSUE TITLE
macOS での ROOT の導入方法

### ISSUE THREAD

**Issue by akira-okumura** [ymapteam/root_lecture#9]
`install/mac.md` で
- Homebrew で GCC を入れる
- Homebrew で ROOT を入れる
の 2 点の説明がありますが、改善したほうが良いように思います。

まず 1 点目ですが、最新の C++ を使用するとかコンパイラのバグがあるとか Clang に対応していないソフトウェアを使用するなど特殊な場合でなければ、macOS に GCC を導入する必要性は高くないと思います。また GCC と Clang の混在により、初心者は混乱することがあるように思います。

次に、Python 環境を Conda などで構築する場合があることを考えると、Homebrew 環境で構築された PyROOT と Conda 環境で構築された他のパッケージ類を同時に使えない（Python のバージョン違いなど）という問題が発生しうるように思います。Conda 環境で ROOT を導入してしまうほうが楽な場面が多いように思います（それはそれで Conda 内の他のパッケージとぶつかる場合もあるのですが）。
https://root.cern/install/#conda

**Comment by mzks** [comment]
コメントありがとうございます.

1点目ですが, 歴史の名残ですのでご指摘の通り削除が適当かと思われます. こちらの環境で確認したのちに修正します.

2点目ですが, どうにも悩ましいです. 実際にbrew で導入するケースは講習会までに環境がどうしても整えられなかった際の非常手段として案内しています. python (と各種ライブラリ) の整合性で問題が発生する可能性は高いのですが, コマンド一発で消せることとを考慮してまずはマクロを動かし始められることを重視しています.
pyenv + conda + ROOTという構築が暫定的にありがちな解だと考えているのですが, プロジェクトに依存し, かつ, 初学者には大変複雑なので, 現状pythonを含めた環境構築は初期段階で案内できないと考えています.
最も, 現在はお示しのリンクのようにROOTのインストールに必ずしも自力buildが必要ない時代が近づいている/すでに到来しているとも感じておりますので, 全般の改訂を検討いたします.
